### ISSUE TITLE
Run everything as non-privileged user

### ISSUE THREAD

**Issue by sadsfae** [vidurous/rhel-labs#18]
I'd like to request that this runs as a non-root user, you might be able to:

- Create non-privileged ```lab-user``` user/group.
- Use sudoers for any virsh related stuff
- Have an easier time with $PATH for some parts of userland.

**Comment by vidurous** [comment]
**Accepted** and slated for Release 1.0.

**Comment by vidurous** [comment]
I'm exporting current paths as `HOME` and defining them dynamically before checking conditional requirements, state files or calling functions. As long as `rhel-labs` and `rhel-labs-functions` are in `/usr/local/sbin/` the script can be executed in any cwd as a native command or using `sudo` assuming `NOPASSWD` is configured for network and virsh commands. 

Something to the effect of: 

*stage 1:*
~~~
export HOME="/home/root/rhel-labs/.<whatever>/<whatever>"

cd $HOME && <something> && <something> || exit echo "oh noes" 
...
do stuff
...
~~~
*stage 2:*
~~~
export HOME="/home/root/<whatever>/.<whatever>/<whatever>"

cd $HOME && <something> && <something> || exit echo "oh noes" 
...
do stuff
...
~~~

I'm thinking of having the user `rhel-labs` and switching to this user `su - rhel-labs` will throw the user into the tui main script, similar to the admin tui on a RHEV-H hypervisor. I can just migrate all paths from `/home/root/rhel-labs/*` to `/home/rhel-labs/rhel-labs` add initial conditional checks to create the user and configure the users `.bashrc` or do something in `/etc/profile.d/`.

**Comment by vidurous** [comment]
***Additional info:*** 
Currently a user makes a choice in the dialog menu prompting to call a function or traverse to another dialog menu; Defining the path in `export HOME="/home/root/<whatever>/.<whatever>/<whatever>"` happens preceding each call to a function or dialog menu hop so we're always locked in a specific cwd.
