### ISSUE TITLE
Cant able to download the lab "RHEL7.2-HOMELAB.tar.gz" file from source

### ISSUE THREAD

**Issue by tempsen** [vidurous/rhel-labs#22]
Hi,

I cant able to download the "RHEL7.2-HOMELAB.tar.gz" from http://irondung.net:8120/training/RHEL7.2-HOMELAB.tar.gz. Please help me to provide correct URL.

Thanks,
Sen

**Comment by vidurous** [comment]
Sure, I’ll open this up over the weekend. This tar archive needs to be pushed to git directly to remove this external dependency. 

Thanks,
Aaron

**Comment by tempsen** [comment]
Hi Aaron,

Thanks, for the consideration. Please modify the as you mentioned, It could be help ful for all of us. Please let me know if you updated. So i can try.

Thanks for your consideration.
Sen

**Comment by vidurous** [comment]
I've resolved this issue however need to update some of this code base.  The project has been on hold and I should have some time to dedicate to it in the near future. 

Thanks, 
Aaron

**Comment by vidurous** [comment]
I've updated master with some previously uncommitted code which is more than likely why I disabled the remote source. Added an rsync dependency temporarily. Everything should now be working.  Give it a try and let me know if you have any issues.

**Comment by vidurous** [comment]
Was testing internally. 

https://github.com/vidurous/rhel-labs/commit/89eae41e718b7c606a12b976c91289ccaeefae55

**Comment by vidurous** [comment]
try again
